package edu.udima.es.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-12-03T23:17:09.950+01:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://edu.udima.es/servicios", name = "ImpuestosServicio")
@XmlSeeAlso({ObjectFactory.class})
public interface ImpuestosServicio {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "aplicarIVA", targetNamespace = "http://edu.udima.es/servicios", className = "edu.udima.es.client.AplicarIVA")
    @WebMethod
    @ResponseWrapper(localName = "aplicarIVAResponse", targetNamespace = "http://edu.udima.es/servicios", className = "edu.udima.es.client.AplicarIVAResponse")
    public java.lang.Float aplicarIVA(
        @WebParam(name = "precioSinIVA", targetNamespace = "")
        java.lang.Float precioSinIVA
    );
}
