
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package edu.udima.es.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-12-03T23:17:09.936+01:00
 * Generated source version: 2.7.13
 * 
 */

@javax.jws.WebService(
                      serviceName = "Impuestos",
                      portName = "ImpuestosServicioPort",
                      targetNamespace = "http://edu.udima.es/servicios",
                      wsdlLocation = "https://impuestosws.herokuapp.com/calculaIVA?wsdl",
                      endpointInterface = "edu.udima.es.client.ImpuestosServicio")
                      
public class ImpuestosServicioImpl implements ImpuestosServicio {

    private static final Logger LOG = Logger.getLogger(ImpuestosServicioImpl.class.getName());

    /* (non-Javadoc)
     * @see edu.udima.es.client.ImpuestosServicio#aplicarIVA(java.lang.Float  precioSinIVA )*
     */
    public java.lang.Float aplicarIVA(java.lang.Float precioSinIVA) { 
        LOG.info("Executing operation aplicarIVA");
        System.out.println(precioSinIVA);
        try {
            java.lang.Float _return = Float.valueOf(0.30459702f);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
