package edu.udima.es.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-12-03T23:17:09.958+01:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "Impuestos", 
                  wsdlLocation = "https://impuestosws.herokuapp.com/calculaIVA?wsdl",
                  targetNamespace = "http://edu.udima.es/servicios") 
public class Impuestos extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://edu.udima.es/servicios", "Impuestos");
    public final static QName ImpuestosServicioPort = new QName("http://edu.udima.es/servicios", "ImpuestosServicioPort");
    static {
        URL url = null;
        try {
            url = new URL("https://impuestosws.herokuapp.com/calculaIVA?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Impuestos.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://impuestosws.herokuapp.com/calculaIVA?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Impuestos(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Impuestos(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Impuestos() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Impuestos(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Impuestos(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Impuestos(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ImpuestosServicio
     */
    @WebEndpoint(name = "ImpuestosServicioPort")
    public ImpuestosServicio getImpuestosServicioPort() {
        return super.getPort(ImpuestosServicioPort, ImpuestosServicio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImpuestosServicio
     */
    @WebEndpoint(name = "ImpuestosServicioPort")
    public ImpuestosServicio getImpuestosServicioPort(WebServiceFeature... features) {
        return super.getPort(ImpuestosServicioPort, ImpuestosServicio.class, features);
    }

}
